import os
import sqlite3
import psycopg
from psycopg import sql

# ---------------------------------------------------------
# DATABASE SETTINGS
# ---------------------------------------------------------
SQLITE_DB = "hardware_inventory.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set.")

sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row

pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False

# These table structures match the uploaded app.py/database.
table_definitions = {
    "users": [
        "user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT UNIQUE NOT NULL",
        "email TEXT UNIQUE NOT NULL",
        "password TEXT NOT NULL",
        "role TEXT NOT NULL DEFAULT 'USER'",
        "status TEXT NOT NULL DEFAULT 'ACTIVE'",
    ],
    "hardware": [
        "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_name TEXT UNIQUE NOT NULL",
        "category TEXT NOT NULL",
        "quantity INTEGER NOT NULL DEFAULT 0",
        "unit_price DOUBLE PRECISION NOT NULL DEFAULT 0",
        "status TEXT NOT NULL",
    ],
    "borrow_requests": [
        "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_id BIGINT NOT NULL",
        "username TEXT NOT NULL",
        "quantity INTEGER NOT NULL",
        "request_date TEXT NOT NULL",
        "due_date TEXT NOT NULL",
        "status TEXT NOT NULL DEFAULT 'PENDING'",
        "return_date TEXT",
    ],
    "reset_requests": [
        "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "email TEXT NOT NULL",
        "status TEXT NOT NULL DEFAULT 'PENDING'",
        "request_date TEXT NOT NULL",
    ],
    "reset_password_data": [
        "request_id BIGINT PRIMARY KEY",
        "password_hash TEXT NOT NULL",
    ],
}

# The order keeps referenced/related tables organized.
table_order = [
    "users",
    "hardware",
    "borrow_requests",
    "reset_requests",
    "reset_password_data",
]

try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()
    counts = {}

    # Create PostgreSQL tables.
    for table_name in table_order:
        columns = table_definitions[table_name]
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)
        create_sql = sql.SQL(
            "CREATE TABLE IF NOT EXISTS {} ({})"
        ).format(sql.Identifier(table_name), column_sql)
        pg_cur.execute(create_sql)

    # Migrate each SQLite table.
    for table_name in table_order:
        # Check whether the PostgreSQL destination is empty.
        count_sql = sql.SQL("SELECT COUNT(*) FROM {}").format(
            sql.Identifier(table_name)
        )
        pg_cur.execute(count_sql)
        destination_count = pg_cur.fetchone()[0]

        if destination_count > 0:
            raise RuntimeError(
                f"Destination table '{table_name}' is not empty. "
                "Clear the destination table before migrating again."
            )

        # SQLite needs a normal string, not psycopg.sql.Composed.
        sqlite_cur.execute(
            f'SELECT * FROM "{table_name}"'
        )
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if not rows:
            continue

        source_columns = [
            description[0] for description in sqlite_cur.description
        ]

        column_identifiers = sql.SQL(", ").join(
            sql.Identifier(column) for column in source_columns
        )
        placeholders = sql.SQL(", ").join(
            sql.Placeholder() for _ in source_columns
        )

        insert_sql = sql.SQL(
            "INSERT INTO {} ({}) VALUES ({})"
        ).format(
            sql.Identifier(table_name),
            column_identifiers,
            placeholders,
        )

        for row in rows:
            values = [row[column] for column in source_columns]
            pg_cur.execute(insert_sql, values)

    # Synchronize identity sequences for auto-increment columns.
    sequence_columns = {
        "users": "user_id",
        "hardware": "item_id",
        "borrow_requests": "request_id",
        "reset_requests": "request_id",
    }

    for table_name, id_column in sequence_columns.items():
        sequence_sql = sql.SQL(
            """
            SELECT setval(
                pg_get_serial_sequence(%s, %s),
                COALESCE(MAX({}), 1),
                MAX({}) IS NOT NULL
            )
            FROM {}
            """
        ).format(
            sql.Identifier(id_column),
            sql.Identifier(id_column),
            sql.Identifier(table_name),
        )

        # Use the PostgreSQL table and column names as parameters.
        pg_cur.execute(
            sequence_sql,
            (table_name, id_column),
        )

    pg_conn.commit()

    print("Migration completed successfully.")
    for table_name in table_order:
        print(f"  {table_name}: {counts[table_name]}")

except Exception:
    pg_conn.rollback()
    raise

finally:
    sqlite_conn.close()
    pg_conn.close()
